### ISSUE TITLE
Exception when adding reaction in private channel

### ISSUE THREAD

**Issue by HeyBanditoz** [ygimenez/Pagination-Utils#5]
**Checklist**

Make sure that you've checked all the items below.

- [x] Bot has the following permissions:
  - MESSAGE_MANAGE
  - MESSAGE_ADD_REACTION
  - MESSAGE_EXT_EMOJI
  - MESSAGE_READ/WRITE
  - VIEW_CHANNEL
- [x] PaginationUtils is up-to-date.
- [x] You have activated the library as descripted in the README.

**Library info**

What libraries versions are you using.
- JDA version 4.2.0_210
- PaginationUtils version 1.2.5b

**Describe the bug**

An exception is thrown when the other user in a DM reacts to a message.

**To Reproduce**

1. Send a message to the bot privately.
2. React to it.
3. Observe the error.

**Expected behavior**

No exception to be thrown.

**Screenshots**

N/A

**Additional context**

Stack trace:
```
03:24:26:863 ERROR [JDA MainWS-ReadThread] net.dv8tion.jda.api.JDA - One of the EventListeners had an uncaught exception
java.lang.IllegalStateException: This message event did not happen in a text channel
	at net.dv8tion.jda.api.events.message.GenericMessageEvent.getTextChannel(GenericMessageEvent.java:147)
	at net.dv8tion.jda.api.events.message.GenericMessageEvent.getGuild(GenericMessageEvent.java:126)
	at com.github.ygimenez.listener.MessageHandler.onMessageReactionAdd(MessageHandler.java:31)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:440)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:147)
	at net.dv8tion.jda.internal.handle.MessageReactionHandler.onAdd(MessageReactionHandler.java:187)
	at net.dv8tion.jda.internal.handle.MessageReactionHandler.handleInternally(MessageReactionHandler.java:159)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:948)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:835)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:813)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:986)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by ygimenez** [comment]
Issue fixed in [release 1.3.0](https://github.com/ygimenez/Pagination-Utils/tree/1.3.0)
